using NoteVui.Domain.Entities.Common;
using NoteVui.Domain.Enums;

namespace NoteVui.Domain.Entities;

/// <summary>
/// Tracks AI usage for quota management and analytics.
/// Each record represents a single AI API call attempt.
/// </summary>
public class AiUsageLog : BaseEntity
{
    /// <summary>
    /// The ID of the user who made the AI request.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// The type of AI action performed (Summarize, FixGrammar, etc.).
    /// </summary>
    public AiActionType ActionType { get; set; }

    /// <summary>
    /// Number of input tokens consumed by this request.
    /// </summary>
    public int InputTokens { get; set; }

    /// <summary>
    /// Number of output tokens generated by this request.
    /// </summary>
    public int OutputTokens { get; set; }

    /// <summary>
    /// Optional reference to the note this AI action was performed on.
    /// </summary>
    public Guid? NoteId { get; set; }

    /// <summary>
    /// The AI provider used (e.g., "Gemini", "OpenAI").
    /// </summary>
    public string Provider { get; set; } = "Gemini";

    /// <summary>
    /// Indicates whether the AI request was successful.
    /// </summary>
    public bool IsSuccess { get; set; }

    /// <summary>
    /// Error message if the request failed.
    /// </summary>
    public string? ErrorMessage { get; set; }
}
